# Generated by Django 3.2.1 on 2021-05-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
