# Generated by Django 3.2.1 on 2021-05-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsslider',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
